### PR TITLE
merge with progress in Heisig's RTK

### PR DESCRIPTION
**Pull request by JonnyJD**
I am learning with Heisings Remember the Kanji (RTK) and WaniKani together,
because I want to learn as many kanji in a month (the preparation time before I got to Japan),
I am using RTK in german and WK in english, so the confusion is not that big of a deal.

So this pull request will show RTK progress together with WK progress (taking precedence).
I don't expect that this will be pulled, but this is a good way to "announce" this patch for others to use.

You can provide the highest Heisig index
with
-i <index>
--heisig-index <index>

You can also set the --heisig-color,
which is green by default. (matrix like..)

The heisig color will only be displayed
when the kanji is unseen in WaniKani.
Otherwise the WaniKani color will be shown.

The kanji order was replaced with the
6th edition Heisig RTK order (2200 kanji)
One additional kanji that is only in WaniKani
was added at the end (after i had an error message).
More might need to be added (I don't have the paid WK for now).

### CODE REVIEW

**Comment by JonnyJD** [comment]
I changed the code to make the order for the wallpaper and the heisig order independent.
I am using the JLPT ordering (from http://peterkinnaird.eu/kani/#kanji) now.
This gives a much nicer "randimization" and makes more sense as JLPT is often the goal.

wanikani_heisig_example_by_usage

**Comment by Hexagenic** [comment]
:+1: I'll evaluate this and merge it later tonight. 

Code looks good.

**Comment by Hexagenic** [comment]
Only change I did was to set the default color of the heisig characters to a light gray instead of green to better match the wanikani colour scheme.

**Comment by JonnyJD** [comment]
great and good job with the original code
The style isn't perfect, but it was easy enough to adapt :-)

**Pull request merged**
